
 export const KNIVES_API_REQUEST = "KNIVES_API_REQUEST";
 export const BOWLS_API_REQUEST = "BOWLS_API_REQUEST";
 export const STATUES_API_REQUEST = "STATUES_API_REQUEST";

 export const KNIVES_API_SUCCESS = "KNIVES_API_SUCCESS"
 export const BOWLS_API_SUCCESS = "BOWLS_API_SUCCESS";
 export const STATUES_API_SUCCESS = "STATUES_API_SUCCESS";

 export const KNIVES_API_FAILURE = "KNIVES_API_FAILURE";
 export const BOWLS_API_FAILURE = "BOWLS_API_FAILURE";
 export const STATUES_API_FAILURE = "STATUES_API_FAILURE"; 
