const NAILS_API_REQUEST = 'NAILS_API_REQUEST';
const NAILS_API_SUCCESS = 'NAILS_API_SUCCESS';
const NAILS_API_FAILURE = 'NAILS_API_FAILURE';

const LASHS_API_REQUEST = 'LASHS_API_REQUEST';
const LASHS_API_SUCCESS =  'LASHS_API_SUCCESS';
const LASHS_API_FAILURE = 'LASHS_API_SUCCESS';

const ACCESSORIES_API_REQUEST = 'ACCESSORIES_API_REQUEST';
const ACCESSORIES_API_SUCCESS = 'ACCESSORIES_API_SUCCESS';
const ACCESSORIES_API_FAILURE = 'ACCESSORIES_API_FAILURE';

const GET_ITEM_INFO_REQUEST = 'GET_ITEM_INFO_REQUEST';
const GET_ITEM_INFO_SUCCESS = 'GET_ITEM_INFO_SUCCESS';
const GET_ITEM_INFO_FAILURE = 'GET_ITEM_INFO_FAILURE';  
